baseurl = "http://richardsumilang.com/"
languageCode = "en-us"
title = "Top Secret Labs - Richard Sumilang"
theme = "hugo-theme-richardsumilang-dark"

[author]
  name = "Richard Sumilang"
  homepage = "http://richardsumilang.com"

[indexes]
  category = "categories"
  tag = "tags"

[Params]
  AmazonAffiliate = "http://www.amazon.com?_encoding=UTF8&tag=topseclabrics-20"
  AuthorName = "Richard"
  Bitbucket = "rsumilang"
  Disqus = "richardsumilang"
  Domain = "richardsumilang.com"
  Email = "me@richardsumilang.com"
  Facebook = "pages/Richard-Sumilang/1671943293041280"
  GitHub = "rsumilang"
  GooglePlus = "103897788753346013902"
  GoogleAnalytics = "UA-38936074-1"
  Instagram = "RichardSumilang"
  Linkedin = "richardsumilang"
  Logo = "images/header-logo.png"
  NewsletterUrl = "http://eepurl.com/bwckhL"
  Pinterest = "rsumilang"
  Twitter = "rsumilang"
  YouTube = "UCoa8wraKQsA95Y691K4kTsA"
  SiteName = "Top Secret Labs"
